### ISSUE TITLE
Edit default snippets not working?

### ISSUE THREAD

**Issue by mbadros** [math2001/BetterSnippetMaker#7]
Thanks for your work on this package.

I don't see the list of (pre-installed) snippets when I try to edit the snippets using BetterSnippetManager.  For example, I wanted to update the 'jquery' snippet to reflect a later version of the jquery CDN. The snippet works, and I can create a new snippet, but I don't see how to list the available snippets or to edit them. I'm using Sublime Text 3.0 (Build 3143) ... with SaneSnippets installed as well.

Thanks for any assistance!
Mark

**Comment by math2001** [comment]
Default snippets (pre-installed as you say) aren't suppose to be listed, since you aren't meant to edit them often. You can always override them "manually" though. Do you agree?

**Comment by mbadros** [comment]
Okay, I understand your reasoning. How can I override them manually? Thanks.

**Comment by math2001** [comment]
Do you have `PackageResourceViewer` installed? Once it is, search for `OpenResource` in the command palette, edit the file and save. Sublime text will then be able to use *your* version, instead of the default one (because your's will be in `Packages`, while the default one are zipped in a `.sublime-package`).
